# -*- coding: utf-8 -*-
"""stackAPI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xzqakc1LMoyIbRG9886yGD8ZXdt-mvpp
"""

from stackapi import StackAPI
SITE = StackAPI('stackoverflow')
SITE.max_pages=2
SITE.page_size=100
questions = SITE.fetch('questions',order='desc',tagged='python',site='stackoverflow')

print(len(questions['items']))

for quest in questions['items']:
    if 'title' not in quest or quest['is_answered'] == False:
        continue
    title = quest['title'] 
    #print('Question :- {0}'.format(title))
    question_id = quest['question_id']
    #print('Question ID :- {0}'.format(question_id))
    top_answer = SITE.fetch('questions/' + str(question_id) + '/answers', order = 'desc', sort='votes')
    if 'accepted_answer_id' in quest.keys():
      accepted_answer_id = quest['accepted_answer_id']
      #print('Accepted Answer ID :- {0}'.format(accepted_answer_id))
    #print("\n----------------------------------------------------------------\n")